### ISSUE TITLE
The 'all contributors' badge is on a different line in the README

### ISSUE THREAD

**Issue by MrHedmad** [CMA-Lab/MTP-DB#35]
This is a relevant issue: https://github.com/all-contributors/all-contributors/issues/361

For beauty's sake we should find a way to fix this, but it's extremely low priority.

**Comment by PotuRevanth** [comment]
> This is a relevant issue: [all-contributors/all-contributors#361](https://github.com/all-contributors/all-contributors/issues/361)
> 
> For beauty's sake we should find a way to fix this, but it's extremely low priority.

assign me the issue. I will fix it.
